# Generated by Django 4.2.1 on 2023-06-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0002_rename_displayname_user_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='musicdjangoAPP.user'),
            preserve_default=False,
        ),
    ]
