# Generated by Django 4.2.1 on 2023-06-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0004_remove_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicdjangoAPP.user'),
            preserve_default=False,
        ),
    ]
