# Generated by Django 4.2.1 on 2023-06-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0006_remove_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
