# Generated by Django 4.2.1 on 2023-06-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0007_song_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='username',
        ),
    ]
