# Generated by Django 4.2.1 on 2023-06-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0008_remove_song_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='username',
            field=models.CharField(default='hee', max_length=25),
            preserve_default=False,
        ),
    ]
