# Generated by Django 4.2.1 on 2023-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0016_alter_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaderID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
