# Generated by Django 4.2.1 on 2023-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0017_song_uploaderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='songsLiked',
            field=models.ManyToManyField(to='musicdjangoAPP.song'),
        ),
    ]
