# Generated by Django 4.2.1 on 2023-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0018_user_songsliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='songsLiked',
            field=models.ManyToManyField(blank=True, to='musicdjangoAPP.song'),
        ),
    ]
