# Generated by Django 4.2.1 on 2023-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0021_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='creatorID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
