# Generated by Django 4.2.1 on 2023-06-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0024_alter_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromID', models.IntegerField()),
                ('toID', models.IntegerField()),
                ('content', models.CharField(max_length=25)),
            ],
        ),
    ]
