# Generated by Django 4.2.1 on 2023-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
