# Generated by Django 4.2.1 on 2023-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdjangoAPP', '0026_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
    ]
